spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rlajm1203/SpringCloudConfig.git
          search-paths: file/**
          default-label: main