spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import:
      # ??? ?? ?? ??? (????? user.dir? ??)
      - "file:./env/main-api.properties"
      - "file:./env/main-api.yml"
      #?? ? application.yml
      - "classpath:application-domain-jpa.yml"
      - "classpath:application-api-query-jpa.yml"
      - "classpath:application-logging.yml"
      - "classpath:application-redis.yml"

server:
  port: 2470 # 24?? ?? + main-api?? 0??

frontend:
  main: # ?? ??? ??
    base-url: ${FRONTEND.MAIN.BASE-URL} # ???? ??
  network-api: # ???? api? ??? ?? (?? ??? ??)
    base-urls: ${FRONTEND.NETWORK-API.BASE-URLS} # ?? ?? (network-api? ?? ?? ? ????)

api-key: ${API_KEY}

https-enabled: ${HTTPS_ENABLED}

oauth:
  redirect-uri: ${OAUTH_REDIRECT_URL}
  kakao:
    secret: ${KAKAO_SECRET}
    clientId : ${KAKAO_CLIENT_ID}

jwt:
  secret: ${JWT.SECRET}
  access-token-expiry: ${JWT.ACCESS-TOKEN-EXPIRY}
  refresh-token-expiry: ${JWT.REFRESH-TOKEN-EXPIRY}
  oauth2-temp-token-expiry: ${JWT.OAUTH2-TEMP-TOKEN-EXPIRY}
  device-register-token-expiry: ${JWT.DEVICE-REGISTER-TOKEN-EXPIRY}

#logging:
#  level:
#      org.springframework.security: DEBUG